version: '3.8'

services:
  srs:
    image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5
    container_name: srs
    ports:
      - "1935:1935"
      - "1985:1985"
      - "8080:8080"
    stdin_open: true
    tty: true
    restart: unless-stopped

  app:
    build: .
    container_name: video-api
    ports:
      - "28001:28001"
    environment:
      - RTSP_URL=rtsp://admin:qazwsx168@192.168.158.195:554/Streaming/Channels/101
      - INFER_URL=http://116.238.240.2:31676/packet
    volumes:
      - ./:/app
    depends_on:
      - srs
    restart: unless-stopped

  ffmpeg-stream:
    image: linuxserver/ffmpeg
    container_name: ffmpeg-stream
    # 不要覆盖 entrypoint！直接用 command 传 ffmpeg 参数
    command: >
      -rtsp_transport tcp
      -i rtsp://admin:qazwsx168@192.168.158.195:554/Streaming/Channels/101
      -c:v libx264 -preset fast -tune zerolatency -b:v 4M
      -c:a aac -b:a 128k
      -f flv rtmp://srs:1935/live/livestream
    depends_on:
      - srs
    restart: unless-stopped

  frontend-dev:
    image: node:22
    container_name: video-frontend-dev
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "4173:4173"
    command: ["/bin/sh", "-c", "npm config set registry https://registry.npmmirror.com && npm install && npm run dev -- --host 0.0.0.0"]
    stdin_open: true
    tty: true
    restart: unless-stopped

  
# ffmpeg -rtsp_transport tcp -i "rtsp://admin:qazwsx168@192.168.158.195:554/Streaming/Channels/101" -c copy -f flv rtmp://localhost:1935/live/livestream
