version: '3.8'

services:
  srs:
    image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5
    container_name: srs
    ports:
      - "1935:1935"
      - "1985:1985"
      - "8081:8080"
    stdin_open: true
    tty: true
    restart: unless-stopped

  app:
    build:
      context: .              # 构建上下文，通常是当前目录
      dockerfile: Dockerfile.jetson  # 指定具体的 Dockerfile 文件名
    container_name: video-api
    ports:
      - "28001:28001"
    environment:
      # 如果 app 需要读取流，建议指向 SRS 的 RTMP/HTTP-FLV 地址
      - RTSP_URL=rtmp://srs:1935/live/livestream 
      - INFER_URL=http://116.238.240.2:31676/packet
    volumes:
      - ./:/app
    privileged: true
    depends_on:
      - srs
    restart: unless-stopped
  
  ffmpeg-stream:
    image: linuxserver/ffmpeg
    container_name: ffmpeg-stream
    # 使用数组格式，避免 YAML 多行字符串解析问题
    command:
      - "-f"
      - "v4l2"
      - "-input_format"
      - "nv12"
      - "-framerate"
      - "25"
      - "-video_size"
      - "640x480"
      - "-thread_queue_size"
      - "512"
      - "-rtbufsize"
      - "256M"
      - "-fflags"
      - "nobuffer"
      - "-flags"
      - "low_delay"
      - "-i"
      - "/dev/video1"
      - "-c:v"
      - "libx264"
      - "-preset"
      - "ultrafast"
      - "-tune"
      - "zerolatency"
      - "-g"
      - "50"
      - "-bf"
      - "0"
      - "-sc_threshold"
      - "0"
      - "-pix_fmt"
      - "yuv420p"
      - "-vsync"
      - "1"
      - "-max_delay"
      - "0"
      - "-an"
      - "-f"
      - "flv"
      - "rtmp://srs:1935/live/livestream"
    devices:
      - "/dev/video1:/dev/video1"
    depends_on:
      - srs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"


  frontend-dev:
    image: node:22
    container_name: video-frontend-dev
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "4173:4173"
    environment:
      - VITE_STREAM_URL=http://192.168.152.6:8081/live/livestream.flv
      - VITE_API_HOST=http://192.168.152.6:28001/api
    command: ["/bin/sh", "-c", "npm config set registry https://registry.npmmirror.com && npm install && npm run dev -- --host 0.0.0.0"]
    stdin_open: true
    tty: true
    restart: unless-stopped