version: '3.8'

services:
  srs:
    image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5
    container_name: srs
    ports:
      - "1935:1935"   # RTMP 推流端口
      - "1985:1985"   # SRS HTTP API 端口
      - "8080:8080"   # HTTP 播放/管理端口
    stdin_open: true
    tty: true
    restart: unless-stopped


# ffmpeg -rtsp_transport tcp -i "rtsp://admin:qazwsx168@192.168.158.195:554/Streaming/Channels/101"   -c:v libx264 -preset fast -tune zerolatency -b:v 4M   -c:a aac -b:a 128k   -f flv rtmp://localhost:1935/live/livestream
